NDefines.NGame.EVENT_TIMEOUT_DEFAULT = 5 --13

NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 0 -- 24
NDefines.NCountry.AIR_VOLUNTEER_PLANES_RATIO = 0
NDefines.NCountry.AIR_VOLUNTEER_BASES_CAPACITY_LIMIT = 1
NDefines.NCountry.BASE_COMMAND_POWER_GAIN = 1 --was 2 in the original mod

NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0.0
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.0
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 0

--NDefines.NMilitary.BASE_FORT_PENALTY = 0.15 --0.15
NDefines.NMilitary.LAND_COMBAT_FORT_DAMAGE_CHANCE = 10 --5
NDefines.NMilitary.UNIT_EXPERIENCE_SCALE = 0.12 --1
--NDefines.NMilitary.UNIT_EXP_LEVELS = { 1, 3, 7.5 , 9 } -- { 0.1, 0.3, 0.75, 0.9 }
NDefines.NMilitary.INFRASTRUCTURE_MOVEMENT_SPEED_IMPACT = -0.05 -- -0.10
NDefines.NMilitary.RETREAT_SPEED_FACTOR = 0.50 -- 0.25
NDefines.NMilitary.WITHDRAWING_SPEED_FACTOR = 0.30 -- 0.15
NDefines.NMilitary.PLANNING_MAX = 0.05 -- 0.30
--NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.02 -- 0.0015
NDefines.NMilitary.TRAINING_MAX_LEVEL = 3 -- 2
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.15 -- 0.25
NDefines.NMilitary.REINFORCE_CHANCE = 0.10 -- 0.02
NDefines.NMilitary.FASTER_ORG_REGAIN_MULT = 1.6 -- 1.0
NDefines.NMilitary.FASTER_ORG_REGAIN_LEVEL = 0.30 -- -0.25
NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -1 -- original mod 1.5 -- vanilla 1
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.009 --0.0015

NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 150 --50
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 10 --100
NDefines.NMilitary.GARRISON_ORDER_ARMY_CAP_FACTOR = 1.0 --3
NDefines.NMilitary.TRAINING_ATTRITION = 0.01 -- 0.05
NDefines.NMilitary.ARMY_TRAINING_FUEL_MULT = 0.15 -- 1

NDefines.NSupply.COOLDOWN_DAYS_AFTER_MOVING_SUPPLY_CAPITAL = 1
NDefines.NSupply.DAYS_TO_START_GIVING_SUPPLY_AFTER_MOVING_SUPPLY_CAPITAL = 1
NDefines.NSupply.DAYS_TO_START_GIVING_FULL_SUPPLY_AFTER_MOVING_SUPPLY_CAPITAL = 1

NDefines.NNavy.AMPHIBIOUS_LANDING_PENALTY = -0.7 -- -0.1

NDefines.NIndustrialOrganisation.DESIGN_TEAM_CHANGE_XP_COST = 0 --5
--NDefines.NMilitary.RIVER_SMALL_STOP_INDEX = 6 --6
--NDefines.NMilitary.RIVER_LARGE_STOP_INDEX = 11 --11 8
NDefines.NMilitary.ENCIRCLED_PENALTY = -0.20 -- -0.75 in es mod -0.30 in vanilla

--NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 9 --4.5
NDefines.NProduction.BASE_FACTORY_SPEED = 5 --2

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999 --500
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999 --500
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999 --500

NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.0025 --0.0001
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY	= 50 --1.2
NDefines.NBuildings.BASE_FACTORY_REPAIR = 4.0 --1.0
NDefines.NBuildings.BASE_FACTORY_REPAIR_FACTOR = 6.0 --2.0 

NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = -0.1
NDefines.NNavy.PRIDE_OF_THE_FLEET_UNASSIGN_COST = 107 -- Force check sum change for updates

NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_ANNEX = 2000
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_FREE = 2000

NDefines.NProduction.BASE_LICENSE_IC_COST = 1000
NDefines.NProduction.LICENSE_IC_COST_YEAR_INCREASE = 0

NDefines.NNavy.NAVAL_INVASION_PREPARE_HOURS = 72
